function write_uboot_platform() {
	echo "we are in write_uboot_platform()"
	echo "we are in write_uboot_platform()"
	echo "we are in write_uboot_platform()"
	echo "we are in write_uboot_platform()"
	echo "we are in write_uboot_platform()"
}
