
BOARD=vbox3
BRANCH=current 
BUILD_DESKTOP=no 
BUILD_MINIMAL=no     # Install common CLI utils
#INSTALL_HEADERS=yes  # Install Linux kernel headers while building. Can be useful for 3rd party drivers
RELEASE=noble